spring.application.name=MS-14-PaymentServiceCircuitBreaker

eureka.client.service-url.default-zone=http://localhost:8761/
server.port=9091

management.endpoints.web.exposure.include=*
management.health.circuitbreakers.enabled=true

## Circuit Breaker Configuration
#resilience4j.circuitbreaker.instances.paymentService.register-health-indicator=true
#resilience4j.circuitbreaker.instances.paymentService.sliding-window-size=10
#resilience4j.circuitbreaker.instances.paymentService.minimum-number-of-calls=5
#resilience4j.circuitbreaker.instances.paymentService.failure-rate-threshold=50
#resilience4j.circuitbreaker.instances.paymentService.wait-duration-in-open-state=10s
#resilience4j.circuitbreaker.instances.paymentService.permitted-number-of-calls-in-half-open-state=3
#resilience4j.circuitbreaker.instances.paymentService.automatic-transition-from-open-to-half-open-enabled=true
#resilience4j.circuitbreaker.instances.paymentService.sliding-window-type=COUNT_BASED