spring.application.name=MS-23-ApiGateway

server.port=9988
spring.cloud.gateway.server.webmvc.routes[0].id=DoctorService
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://MS-23-DoctorService
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/doctor/**

spring.cloud.gateway.server.webmvc.routes[1].id=patient-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://MS-23-PatientService
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/patient/**
