spring.application.name=MS-21-APIGateway
server.port=1010
eureka.client.service-url.default-zone=http://localhost:8761/

spring.cloud.gateway.server.webmvc.routes[0].id=product-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://MS-12-ProductService
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/products/**

spring.cloud.gateway.server.webmvc.routes[1].id=number-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://MS-10-NumberService
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/number/**

