spring.application.name=MS-19-NotificationServiceMonitoring

spring.boot.admin.client.url=http://localhost:9091/
eureka.client.service-url.default-zone=http://localhost:8761/

server.port=4041

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
#management.endpoint.env.enabled=true
management.endpoint.env.show-values=always