spring.application.name=MS-22-ApiGateway

server.port=9988
eureka.client.service-url.default-zone=http://localhost:8761/

spring.cloud.gateway.server.webmvc.routes[0].id=book-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://MS-22-BookService
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/book/**

spring.cloud.gateway.server.webmvc.routes[1].id=member-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://MS-22-MemberService
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/member/**

